library:
  source-dirs: src
tests:
  connect-four-common-test:
    source-dirs: test
    main: Spec.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - connect-four-common
copyright: 2020 Author name here
maintainer: example@example.com
dependencies:
- mtl
- test-framework
- test-framework-hunit
- test-framework-quickcheck2
- HUnit
- QuickCheck
- array
- base >= 4.7 && < 5
name: connect-four-common
version: 0.1.0.0
extra-source-files:
- README.md
- ChangeLog.md
author: Author name here
github: githubuser/connect-four-server
license: BSD3
executables:
  connect-four-common-exe:
    source-dirs: app
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - connect-four-common
description: Please see the README on GitHub at <https://github.com/githubuser/connect-four-server#readme>
